### PR TITLE
Ensure nix-build works in codespaces

### LINKED ISSUE #12: Nix builds fail in codespaces
```
$ nix-build --keep-failed -E 'with import <nixpkgs> {}; writeText "a" "test1234"'
this derivation will be built:
  /nix/store/mn2fsg0fq7ssiwa7p4ra7if14ny82dlk-a.drv
these 28 paths will be fetched (8.34 MiB download, 43.30 MiB unpacked):
  /nix/store/0b6zhyagwcps9qq67sd0qwmsshnjsqs0-findutils-4.9.0
...
  /nix/store/zn25l68l2k0zgsf4vgvyrwsss0axa250-gnumake-4.3
copying path '/nix/store/3j918i1nbwhby0y38bn2r438rjhh8f4d-bash-5.1-p16' from 'https://cache.nixos.org'...
...
copying path '/nix/store/40hd631867iyazhklp24xq9lblpzjvsy-stdenv-linux' from 'https://cache.nixos.org'...
building '/nix/store/mn2fsg0fq7ssiwa7p4ra7if14ny82dlk-a.drv'...
note: keeping build directory '/tmp/nix-build-a.drv-0'
error: suspicious ownership or permission on '/nix/store/3s3d96ls775w952lh5l3iqj76lijzj3w-a' for output 'out'; rejecting this build output
```

E.g. see https://github.com/NixOS/nix/issues/6680. This comment has a solution: https://github.com/NixOS/nix/issues/6680#issuecomment-1230902525, viz run `setfacl -k /tmp`. Not sure yet if it has to be a `postCreateCommand`.

UPDATE: `setfacl -k /tmp` works for me in `Dockerfile` or in a `postCreateCommand`.

UPDATE(2): I tried again and it didn't work in `Dockerfile`. I think maybe the volume for `/nix` was caching the build when I tried before. So that would say we need an `apt-get install acl` in `Dockerfile` and a `postCreateCommand`, which is less nice for this project, but I can deal with it.

### PR DESCRIPTION
**Pull request by dsyer**
Fixes #12

### CODE REVIEW

**Comment by offlinehacker** [comment]
I am thinking whether putting fix into `docker-entrypoint.sh` https://github.com/xtruder/nix-devcontainer/blob/main/src/docker-entrypoint.sh would be better? This will make sure that `devcontainer.json` can be kept as it is.

**Comment by dsyer** [comment]
I think codespaces ignores the entry point from the container anyway, so maybe that won't work (and maybe that will cause other issues)? I'll try it.

**Comment by offlinehacker** [comment]
Regarding testing, I have created [`devcontainer.json`][1] for codespaces testing, that uses `src/Dockerfile` directly and you can use it without pushing docker image. You will need to select `.devcontainer/codespaces/devcontainer.json` when creating codespace:

image


[1]: https://github.com/xtruder/nix-devcontainer/blob/main/.devcontainer/codespaces/devcontainer.json

**Comment by offlinehacker** [comment]
I assume this option is also available if you fork this repo and do it on your personal accounts.

**Comment by offlinehacker** [comment]
@dsyer entrypoint seems to work for me. In what cases did you saw issues with entrypoint?

**Pull request closed without merging**
